version: "3.7"
services:


  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      PORT: 8080
    depends_on:
      - postgres
